[2025-04-08T10:04:06.315+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T10:04:06.392+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-08T10:04:06.419+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-08T10:04:06.430+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-04-08T10:04:07.115+0000] {taskinstance.py:2889} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2025-04-05 00:00:00+00:00
[2025-04-08T10:04:07.178+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5533) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T10:04:07.197+0000] {standard_task_runner.py:72} INFO - Started process 5544 to run task
[2025-04-08T10:04:07.171+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v04', 'sensor_minio_s3', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '1003', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmptopkxmic']
[2025-04-08T10:04:07.218+0000] {standard_task_runner.py:105} INFO - Job 1003: Subtask sensor_minio_s3
[2025-04-08T10:04:07.628+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 scheduled__2025-04-05T00:00:00+00:00 [running]> on host e9ff53ca7e24
[2025-04-08T10:04:08.176+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acilrest12' AIRFLOW_CTX_DAG_ID='dag_with_minio_s3_v04' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-08T10:04:08.178+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-08T10:04:08.249+0000] {baseoperator.py:416} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-04-08T10:04:08.258+0000] {s3.py:116} INFO - Poking for key : s3://***/data.csv
[2025-04-08T10:04:08.313+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-04-08T10:04:08.315+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-04-08T10:04:10.167+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-04-08T10:04:10.233+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-08T10:04:10.237+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_minio_s3_v04, task_id=sensor_minio_s3, run_id=scheduled__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250408T100406, end_date=20250408T100410
[2025-04-08T10:04:10.441+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T10:04:10.556+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T10:04:10.587+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
