[2025-03-29T14:56:50.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-29T14:56:50.785+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fist_dag_v5.second_task scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-03-29T14:56:51.054+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fist_dag_v5.second_task scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-03-29T14:56:51.069+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-03-29T14:56:51.196+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2025-01-18 00:00:00+00:00
[2025-03-29T14:56:51.268+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=862) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-29T14:56:51.299+0000] {standard_task_runner.py:72} INFO - Started process 888 to run task
[2025-03-29T14:56:51.256+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fist_dag_v5', 'second_task', 'scheduled__2025-01-18T00:00:00+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpw04mlrk9']
[2025-03-29T14:56:51.325+0000] {standard_task_runner.py:105} INFO - Job 325: Subtask second_task
[2025-03-29T14:56:51.802+0000] {task_command.py:467} INFO - Running <TaskInstance: fist_dag_v5.second_task scheduled__2025-01-18T00:00:00+00:00 [running]> on host ba06481f48a9
[2025-03-29T14:56:52.677+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='fist_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-18T00:00:00+00:00'
[2025-03-29T14:56:52.685+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-29T14:56:52.967+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-29T14:56:53.011+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, i am task2 and will be running after task1!']
[2025-03-29T14:56:53.291+0000] {subprocess.py:99} INFO - Output:
[2025-03-29T14:56:53.386+0000] {subprocess.py:106} INFO - hey, i am task2 and will be running after task1!
[2025-03-29T14:56:53.404+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-29T14:56:53.683+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-29T14:56:53.695+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fist_dag_v5, task_id=second_task, run_id=scheduled__2025-01-18T00:00:00+00:00, execution_date=20250118T000000, start_date=20250329T145650, end_date=20250329T145653
[2025-03-29T14:56:53.894+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-29T14:56:53.986+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-29T14:56:54.041+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
